spring:
  application:
    name: eureka-server-repli
eureka:
  client:
    serviceUrl:
      defaultZone: http://pee1:8761/eureka/,http://pee2:8762/eureka/
  instance:
    hostname: pee2
server:
  port: 8762
